"""empty message

Revision ID: 122e7f1f8b73
Revises: None
Create Date: 2014-08-20 02:43:15.447000

"""

# revision identifiers, used by Alembic.
revision = '122e7f1f8b73'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('photo', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'photo')
    ### end Alembic commands ###
