"""empty message

Revision ID: 18e6418622eb
Revises: 141b4dcc4bb4
Create Date: 2014-08-10 00:08:42.770000

"""

# revision identifiers, used by Alembic.
revision = '18e6418622eb'
down_revision = '141b4dcc4bb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
