"""empty message

Revision ID: 1c6f3a368bdf
Revises: 1410ed86eab0
Create Date: 2014-09-19 18:11:22.981000

"""

# revision identifiers, used by Alembic.
revision = '1c6f3a368bdf'
down_revision = '1410ed86eab0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
