"""empty message

Revision ID: 1e240ee4d08d
Revises: 122e7f1f8b73
Create Date: 2014-09-18 18:04:05.833000

"""

# revision identifiers, used by Alembic.
revision = '1e240ee4d08d'
down_revision = '122e7f1f8b73'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category1', sa.String(length=255), nullable=True))
    op.add_column('article', sa.Column('category2', sa.String(length=255), nullable=True))
    op.drop_column('article', 'category')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('article', 'category2')
    op.drop_column('article', 'category1')
    ### end Alembic commands ###
