"""empty message

Revision ID: 28424c80441
Revises: 53a9650af22e
Create Date: 2014-08-10 17:25:30.781000

"""

# revision identifiers, used by Alembic.
revision = '28424c80441'
down_revision = '53a9650af22e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
