"""empty message

Revision ID: 46275bbaa78e
Revises: 3723f82b8a3
Create Date: 2014-08-10 14:21:43.077000

"""

# revision identifiers, used by Alembic.
revision = '46275bbaa78e'
down_revision = '3723f82b8a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('like', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('like', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'like')
    op.drop_column('article', 'like')
    ### end Alembic commands ###
