"""empty message

Revision ID: 475232bd0513
Revises: 1e240ee4d08d
Create Date: 2014-09-18 18:28:39.380000

"""

# revision identifiers, used by Alembic.
revision = '475232bd0513'
down_revision = '1e240ee4d08d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
