"""empty message

Revision ID: 53a9650af22e
Revises: 46275bbaa78e
Create Date: 2014-08-10 17:10:00.415000

"""

# revision identifiers, used by Alembic.
revision = '53a9650af22e'
down_revision = '46275bbaa78e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
